file(GLOB libs "${src}/*.dylib" "${src}/*.so")
foreach(lib ${libs})
	get_filename_component(name ${lib} NAME)
	if(NOT EXISTS "${lib}")
		continue()
	endif()
	if(IS_SYMLINK "${lib}")
		get_filename_component(real_lib ${lib} REALPATH)
		if(NOT EXISTS "${real_lib}")
			continue()
		endif()
		get_filename_component(real_name ${real_lib} NAME)
		execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${real_lib} ${dst}/${real_name})
		if(NOT "${real_name}" STREQUAL "${name}")
			file(CREATE_LINK "${real_name}" "${dst}/${name}" SYMBOLIC)
		endif()
	else()
		execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${lib} ${dst}/${name})
	endif()
endforeach()
