function(dep_path line out_var)
	string(STRIP "${line}" line)
	string(REGEX REPLACE " \\(.*\\)$" "" line "${line}")
	set(${out_var} "${line}" PARENT_SCOPE)
endfunction()

function(is_external_dep path out_var)
	set(ok OFF)
	if(path MATCHES "^/opt/homebrew/" OR path MATCHES "^/usr/local/")
		set(ok ON)
	endif()
	set(${out_var} ${ok} PARENT_SCOPE)
endfunction()

function(bundle_id path out_var)
	if(path MATCHES "([^/]+\\.framework/Versions/[^/]+/[^/]+)$")
		set(${out_var} "${BUNDLE_RPATH}/${CMAKE_MATCH_1}" PARENT_SCOPE)
	else()
		get_filename_component(name "${path}" NAME)
		set(${out_var} "${BUNDLE_RPATH}/${name}" PARENT_SCOPE)
	endif()
endfunction()

function(rewrite_id f)
	execute_process(COMMAND otool -D "${f}" OUTPUT_VARIABLE out ERROR_QUIET)
	string(REPLACE "\n" ";" lines "${out}")
	list(LENGTH lines n)
	if(n LESS 2)
		return()
	endif()
	list(GET lines 1 id_name)
	string(STRIP "${id_name}" id_name)
	if(id_name STREQUAL "" OR id_name MATCHES "^@")
		return()
	endif()
	bundle_id("${id_name}" new_id)
	execute_process(COMMAND install_name_tool -id "${new_id}" "${f}" ERROR_QUIET)
endfunction()

function(rewrite_deps f)
	execute_process(COMMAND otool -L "${f}" OUTPUT_VARIABLE out ERROR_QUIET)
	string(REPLACE "\n" ";" lines "${out}")
	foreach(line ${lines})
		dep_path("${line}" dep)
		is_external_dep("${dep}" ext)
		if(NOT ext)
			continue()
		endif()
		bundle_id("${dep}" new_dep)
		execute_process(COMMAND install_name_tool -change "${dep}" "${new_dep}" "${f}" ERROR_QUIET)
	endforeach()
endfunction()

function(rewrite_rpaths f)
	execute_process(COMMAND otool -l "${f}" OUTPUT_VARIABLE out ERROR_QUIET)
	string(REGEX REPLACE "\r?\n" ";" lines "${out}")
	set(expect_path OFF)
	set(has_bundle_rpath OFF)
	foreach(line ${lines})
		if(line MATCHES "cmd +LC_RPATH")
			set(expect_path ON)
		elseif(expect_path AND line MATCHES "path +([^ ]+)")
			set(expect_path OFF)
			set(rp "${CMAKE_MATCH_1}")
			if(rp STREQUAL "${BUNDLE_RPATH}")
				set(has_bundle_rpath ON)
			elseif(NOT rp MATCHES "^@")
				execute_process(COMMAND install_name_tool -delete_rpath "${rp}" "${f}" ERROR_QUIET)
			endif()
		elseif(line MATCHES "cmd +LC_")
			set(expect_path OFF)
		endif()
	endforeach()
	if(NOT has_bundle_rpath)
		execute_process(COMMAND install_name_tool -add_rpath "${BUNDLE_RPATH}" "${f}" ERROR_QUIET)
	endif()
endfunction()

function(framework_dep path out_var)
	if(path MATCHES "([^/]+\\.framework)/")
		set(${out_var} "${CMAKE_MATCH_1}" PARENT_SCOPE)
	else()
		set(${out_var} "" PARENT_SCOPE)
	endif()
endfunction()

function(prune_unused_frameworks seeds)
	set(queue ${seeds})
	set(needed)
	while(queue)
		list(GET queue 0 f)
		list(REMOVE_AT queue 0)
		if(NOT EXISTS "${f}")
			continue()
		endif()
		execute_process(COMMAND otool -L "${f}" OUTPUT_VARIABLE out ERROR_QUIET)
		string(REPLACE "\n" ";" lines "${out}")
		foreach(line ${lines})
			dep_path("${line}" dep)
			framework_dep("${dep}" fw)
			if(fw STREQUAL "" OR fw IN_LIST needed)
				continue()
			endif()
			list(APPEND needed ${fw})
			get_filename_component(fw_name "${fw}" NAME_WE)
			file(GLOB fw_bin "${FW_DIR}/${fw}/Versions/*/${fw_name}")
			list(APPEND queue ${fw_bin})
		endforeach()
	endwhile()
	file(GLOB bundled "${FW_DIR}/*.framework")
	foreach(fw_path ${bundled})
		get_filename_component(fw "${fw_path}" NAME)
		if(NOT fw IN_LIST needed)
			message(STATUS "Removing unused ${fw}")
			file(REMOVE_RECURSE "${fw_path}")
		endif()
	endforeach()
endfunction()
