cmake_minimum_required(VERSION 3.12)

if(NOT BUNDLE OR NOT EXECUTABLE_NAME)
    message(FATAL_ERROR "BUNDLE and EXECUTABLE_NAME must be set")
endif()

set(frameworks_dir "${BUNDLE}/Contents/Frameworks")

set(macho_files "${BUNDLE}/Contents/MacOS/${EXECUTABLE_NAME}")
file(GLOB fw "${frameworks_dir}/*.dylib" "${frameworks_dir}/*.so")
list(APPEND macho_files ${fw})
file(GLOB_RECURSE pl "${BUNDLE}/Contents/PlugIns/*.dylib")
list(APPEND macho_files ${pl})

foreach(f ${macho_files})
    if(NOT EXISTS "${f}")
        continue()
    endif()

    execute_process(COMMAND otool -l "${f}"
                    OUTPUT_VARIABLE out OUTPUT_STRIP_TRAILING_WHITESPACE)

    string(REGEX REPLACE "\r?\n" ";" lines "${out}")
    set(expect_path OFF)
    set(expect_id OFF)

    foreach(line ${lines})
        if(line MATCHES "cmd +LC_RPATH")
            set(expect_path ON)
            set(expect_id OFF)
        elseif(line MATCHES "cmd +LC_ID_DYLIB")
            set(expect_id ON)
            set(expect_path OFF)
        elseif(expect_path AND line MATCHES "path +([^ ]+)")
            set(rp "${CMAKE_MATCH_1}")
            string(SUBSTRING "${rp}" 0 1 c)
            if(NOT c STREQUAL "@")
                execute_process(COMMAND install_name_tool -delete_rpath "${rp}" "${f}"
                                OUTPUT_QUIET ERROR_QUIET)
            endif()
            set(expect_path OFF)
        elseif(expect_id AND line MATCHES "name +([^ ]+)")
            set(id_name "${CMAKE_MATCH_1}")
            string(SUBSTRING "${id_name}" 0 1 c)
            if(NOT c STREQUAL "@")
                get_filename_component(basename "${id_name}" NAME)
                execute_process(COMMAND install_name_tool -id "@rpath/${basename}" "${f}"
                                OUTPUT_QUIET ERROR_QUIET)
            endif()
            set(expect_id OFF)
        elseif(line MATCHES "cmd +LC_" AND (expect_path OR expect_id))
            set(expect_path OFF)
            set(expect_id OFF)
        endif()
    endforeach()
endforeach()

file(GLOB framework_bundles "${frameworks_dir}/*.framework")
foreach(fb ${framework_bundles})
    execute_process(COMMAND codesign --force --sign - "${fb}" OUTPUT_QUIET ERROR_QUIET)
endforeach()
foreach(f ${macho_files})
    if(NOT EXISTS "${f}")
        continue()
    endif()
    execute_process(COMMAND codesign --force --sign - "${f}" OUTPUT_QUIET ERROR_QUIET)
endforeach()
execute_process(COMMAND codesign --force --sign - "${BUNDLE}" OUTPUT_QUIET ERROR_QUIET)
