# Relocate FLibrary.app: rewrite Homebrew paths and keep only required Qt plugins.
cmake_minimum_required(VERSION 3.12)

if(NOT BUNDLE OR NOT EXECUTABLE_NAME)
	message(FATAL_ERROR "BUNDLE and EXECUTABLE_NAME must be set")
endif()

set(FW_DIR "${BUNDLE}/Contents/Frameworks")
set(BUNDLE_RPATH "@executable_path/../Frameworks")

function(dep_path line out_var)
	string(STRIP "${line}" line)
	string(REGEX REPLACE " \\(.*\\)$" "" line "${line}")
	set(${out_var} "${line}" PARENT_SCOPE)
endfunction()

function(bundle_id path out_var)
	if(path MATCHES "([^/]+\\.framework/Versions/[^/]+/[^/]+)$")
		set(${out_var} "${BUNDLE_RPATH}/${CMAKE_MATCH_1}" PARENT_SCOPE)
	else()
		get_filename_component(name "${path}" NAME)
		set(${out_var} "${BUNDLE_RPATH}/${name}" PARENT_SCOPE)
	endif()
endfunction()

function(rewrite_id f)
	execute_process(COMMAND otool -D "${f}" OUTPUT_VARIABLE out ERROR_QUIET)
	string(REPLACE "\n" ";" lines "${out}")
	list(LENGTH lines n)
	if(n LESS 2)
		return()
	endif()
	list(GET lines 1 id_name)
	string(STRIP "${id_name}" id_name)
	if(id_name STREQUAL "" OR id_name MATCHES "^@")
		return()
	endif()
	bundle_id("${id_name}" new_id)
	execute_process(COMMAND install_name_tool -id "${new_id}" "${f}" ERROR_QUIET)
endfunction()

function(rewrite_deps f)
	execute_process(COMMAND otool -L "${f}" OUTPUT_VARIABLE out ERROR_QUIET)
	string(REPLACE "\n" ";" lines "${out}")
	foreach(line ${lines})
		dep_path("${line}" dep)
		if(NOT dep MATCHES "^/opt/homebrew/" AND NOT dep MATCHES "^/usr/local/")
			continue()
		endif()
		bundle_id("${dep}" new_dep)
		execute_process(COMMAND install_name_tool -change "${dep}" "${new_dep}" "${f}" ERROR_QUIET)
	endforeach()
endfunction()

function(rewrite_rpaths f)
	execute_process(COMMAND otool -l "${f}" OUTPUT_VARIABLE out ERROR_QUIET)
	string(REGEX REPLACE "\r?\n" ";" lines "${out}")
	set(expect_path OFF)
	set(has_bundle_rpath OFF)
	foreach(line ${lines})
		if(line MATCHES "cmd +LC_RPATH")
			set(expect_path ON)
		elseif(expect_path AND line MATCHES "path +([^ ]+)")
			set(expect_path OFF)
			set(rp "${CMAKE_MATCH_1}")
			if(rp STREQUAL "${BUNDLE_RPATH}")
				set(has_bundle_rpath ON)
			elseif(NOT rp MATCHES "^@")
				execute_process(COMMAND install_name_tool -delete_rpath "${rp}" "${f}" ERROR_QUIET)
			endif()
		elseif(line MATCHES "cmd +LC_")
			set(expect_path OFF)
		endif()
	endforeach()
	if(NOT has_bundle_rpath)
		execute_process(COMMAND install_name_tool -add_rpath "${BUNDLE_RPATH}" "${f}" ERROR_QUIET)
	endif()
endfunction()

function(collect_binaries out_var)
	set(files "${BUNDLE}/Contents/MacOS/${EXECUTABLE_NAME}")
	if(EXISTS "${BUNDLE}/Contents/MacOS/opds")
		list(APPEND files "${BUNDLE}/Contents/MacOS/opds")
	endif()
	file(GLOB dylibs "${FW_DIR}/*.dylib" "${FW_DIR}/*.so")
	file(GLOB_RECURSE plugins "${BUNDLE}/Contents/PlugIns/*.dylib")
	file(GLOB_RECURSE fw_bins "${FW_DIR}/*.framework/Versions/*/*")
	list(APPEND files ${dylibs} ${plugins})
	foreach(f ${fw_bins})
		get_filename_component(name "${f}" NAME)
		get_filename_component(ver_a "${f}" DIRECTORY)
		get_filename_component(versions "${ver_a}" DIRECTORY)
		get_filename_component(fw_path "${versions}" DIRECTORY)
		get_filename_component(fw "${fw_path}" NAME_WE)
		if(EXISTS "${f}" AND NOT IS_DIRECTORY "${f}" AND name STREQUAL "${fw}")
			list(APPEND files "${f}")
		endif()
	endforeach()
	set(${out_var} ${files} PARENT_SCOPE)
endfunction()

function(keep_listed_plugins)
	if(NOT KEEP_PLUGINS_FILE OR NOT EXISTS "${KEEP_PLUGINS_FILE}")
		message(FATAL_ERROR "KEEP_PLUGINS_FILE is missing")
	endif()
	file(STRINGS "${KEEP_PLUGINS_FILE}" keep)
	set(found)
	file(GLOB_RECURSE plugins "${BUNDLE}/Contents/PlugIns/*.dylib")
	foreach(p ${plugins})
		file(RELATIVE_PATH rel "${BUNDLE}/Contents/PlugIns" "${p}")
		if(rel IN_LIST keep)
			list(APPEND found ${rel})
		else()
			file(REMOVE "${p}")
		endif()
	endforeach()
	foreach(rel ${keep})
		if(rel AND NOT rel IN_LIST found)
			message(FATAL_ERROR "Required Qt plugin missing: ${rel}")
		endif()
	endforeach()
endfunction()

function(verify_clean files)
	set(bad)
	foreach(f ${files})
		if(NOT EXISTS "${f}")
			continue()
		endif()
		execute_process(COMMAND otool -L "${f}" OUTPUT_VARIABLE out ERROR_QUIET)
		execute_process(COMMAND otool -l "${f}" OUTPUT_VARIABLE cmds ERROR_QUIET)
		if(out MATCHES "/opt/homebrew/" OR out MATCHES "/usr/local/" OR cmds MATCHES "path +/opt/homebrew" OR cmds MATCHES "path +/usr/local")
			list(APPEND bad "${f}")
		endif()
	endforeach()
	if(bad)
		string(REPLACE ";" "\n  " listed "${bad}")
		message(FATAL_ERROR "Homebrew paths remain in:\n  ${listed}")
	endif()
endfunction()

function(codesign_all files)
	file(GLOB fws "${FW_DIR}/*.framework")
	foreach(fw ${fws})
		execute_process(COMMAND codesign --force --sign - "${fw}" OUTPUT_QUIET ERROR_QUIET)
	endforeach()
	foreach(f ${files})
		if(EXISTS "${f}")
			execute_process(COMMAND codesign --force --sign - "${f}" OUTPUT_QUIET ERROR_QUIET)
		endif()
	endforeach()
	execute_process(COMMAND codesign --force --sign - "${BUNDLE}" OUTPUT_QUIET ERROR_QUIET)
endfunction()

keep_listed_plugins()
collect_binaries(MACHO)
foreach(f ${MACHO})
	if(EXISTS "${f}")
		rewrite_id("${f}")
		rewrite_deps("${f}")
		rewrite_rpaths("${f}")
	endif()
endforeach()
collect_binaries(MACHO)
verify_clean("${MACHO}")
codesign_all("${MACHO}")
