# Make FLibrary.app relocatable: no Homebrew load commands or rpaths.
cmake_minimum_required(VERSION 3.12)

if(NOT BUNDLE OR NOT EXECUTABLE_NAME)
	message(FATAL_ERROR "BUNDLE and EXECUTABLE_NAME must be set")
endif()

set(FW_DIR "${BUNDLE}/Contents/Frameworks")
set(BUNDLE_RPATH "@executable_path/../Frameworks")
include("${CMAKE_CURRENT_LIST_DIR}/fixup_macho.cmake")

function(collect_binaries out_var)
	set(files "${BUNDLE}/Contents/MacOS/${EXECUTABLE_NAME}")
	if(EXISTS "${BUNDLE}/Contents/MacOS/opds")
		list(APPEND files "${BUNDLE}/Contents/MacOS/opds")
	endif()
	file(GLOB dylibs "${FW_DIR}/*.dylib" "${FW_DIR}/*.so")
	list(APPEND files ${dylibs})
	file(GLOB_RECURSE plugins "${BUNDLE}/Contents/PlugIns/*.dylib")
	list(APPEND files ${plugins})
	if(COLLECT_FRAMEWORKS)
		file(GLOB_RECURSE fw_bins "${FW_DIR}/*.framework/Versions/*/*")
		foreach(f ${fw_bins})
			get_filename_component(name "${f}" NAME)
			get_filename_component(ver_a "${f}" DIRECTORY)
			get_filename_component(versions "${ver_a}" DIRECTORY)
			get_filename_component(fw_path "${versions}" DIRECTORY)
			get_filename_component(fw "${fw_path}" NAME_WE)
			if(EXISTS "${f}" AND NOT IS_DIRECTORY "${f}" AND name STREQUAL "${fw}")
				list(APPEND files "${f}")
			endif()
		endforeach()
	endif()
	set(${out_var} ${files} PARENT_SCOPE)
endfunction()

function(verify_clean files)
	set(bad)
	foreach(f ${files})
		if(NOT EXISTS "${f}")
			continue()
		endif()
		execute_process(COMMAND otool -L "${f}" OUTPUT_VARIABLE out ERROR_QUIET)
		execute_process(COMMAND otool -l "${f}" OUTPUT_VARIABLE cmds ERROR_QUIET)
		if(out MATCHES "/opt/homebrew/" OR out MATCHES "/usr/local/" OR cmds MATCHES "path +/opt/homebrew" OR cmds MATCHES "path +/usr/local")
			list(APPEND bad "${f}")
		endif()
	endforeach()
	if(bad)
		string(REPLACE ";" "\n  " listed "${bad}")
		message(FATAL_ERROR "Homebrew paths remain in:\n  ${listed}")
	endif()
endfunction()

function(codesign_all files)
	file(GLOB fws "${FW_DIR}/*.framework")
	foreach(fw ${fws})
		execute_process(COMMAND codesign --force --sign - "${fw}" OUTPUT_QUIET ERROR_QUIET)
	endforeach()
	foreach(f ${files})
		if(EXISTS "${f}")
			execute_process(COMMAND codesign --force --sign - "${f}" OUTPUT_QUIET ERROR_QUIET)
		endif()
	endforeach()
	execute_process(COMMAND codesign --force --sign - "${BUNDLE}" OUTPUT_QUIET ERROR_QUIET)
endfunction()

file(REMOVE_RECURSE "${BUNDLE}/Contents/PlugIns/platforminputcontexts")
file(REMOVE "${BUNDLE}/Contents/PlugIns/imageformats/libqpdf.dylib")
set(COLLECT_FRAMEWORKS OFF)
collect_binaries(SEEDS)
prune_unused_frameworks("${SEEDS}")
set(COLLECT_FRAMEWORKS ON)
collect_binaries(MACHO)
foreach(f ${MACHO})
	if(EXISTS "${f}")
		rewrite_id("${f}")
		rewrite_deps("${f}")
		rewrite_rpaths("${f}")
	endif()
endforeach()
collect_binaries(MACHO)
verify_clean("${MACHO}")
codesign_all("${MACHO}")
